### PR TITLE
go dep updates

### PR DESCRIPTION
**Pull request by vbatts**
incrementally stepped through all the go deps, update it, and check that it still built

There are still updates to be done, but these seem to have no issue.

### CODE REVIEW

**Comment by invidian** [comment]
All unit tests passing?

**Comment by vbatts** [comment]
@invidian good question.
Running `make test`:
- on flatcar-master: Success
- on this branch: Success

as for using the tools themselves: no idea

**Review by invidian — APPROVED** [review]

**Comment by vbatts** [comment]
cool. now the github actions passes.

**Comment by pothos** [comment]
Was reverted in https://github.com/kinvolk/mantle/pull/147 because it breaks the interaction with the AWS API. We have to revert the revert and fix the problem and properly test it before merging:

```
# set secret variables
./kola run --parallel=1 --basename=jenkins-aws-707 --board=amd64-usr --aws-ami=ami-07ead16a3df6a7bd4 --aws-region=us-west-2 --aws-type=t3.small --aws-iam-profile=jenkins-test --platform=aws --channel=stable cl.basic
```

**Pull request merged**
