### PR TITLE
sdk: pass '--quiet' to repo sync

### PR DESCRIPTION
**Pull request by jepio**
The messages are long and scroll by too fast to be of any use to users. Adding
quiet turns it into a nice progress indicator.

### CODE REVIEW

**Review by sayanchowdhury — APPROVED** [review]
I was thinking of adding this last night! thanks!

**Comment by tormath1** [comment]
Would it be relevant to bind this `--quiet` option to the `--debug` or `--verbose` global flags ?

**Comment by jepio** [comment]
> Would it be relevant to bind this `--quiet` option to the `--debug` or `--verbose` global flags ?

I could do that, but I would need some help. Do you have a suggestion of how I might get access to the loglevel?

**Comment by tormath1** [comment]
From a first look - it seems that each command (`cork`, `kola`, etc.) inherits from the `main` flags:https://github.com/kinvolk/mantle/blob/927a11b7463d8befc3face602e423e52fbd66953/cli/cli.go#L55-L60

We can confirm by running simple commands:
```shell
$ cork create --help
...

Global Flags:
  -d, --debug             Alias for --log-level=DEBUG
      --log-level value   Set global log level. (default NOTICE)
  -v, --verbose           Alias for --log-level=INFO
```

Since we use the `cobra` framework, it should be easy to get back to the parent command to get the `--debug` / `--verbose` flag from the `runCreate`:
https://github.com/kinvolk/mantle/blob/927a11b7463d8befc3face602e423e52fbd66953/cmd/cork/create.go#L224

Using `cmd.Flags().GetBool("verbose")` for example in order to access the value of `--verbose` - not tested but maybe we can access directly the flag with [command.Flag](https://pkg.go.dev/github.com/spf13/cobra#Command.Flag).

Once we have the value, we can propagate it to the `RepoSync` method in a similar way as the `forceSync` variable:
https://github.com/kinvolk/mantle/blob/927a11b7463d8befc3face602e423e52fbd66953/cmd/cork/create.go#L285-L287

**Comment by jepio** [comment]
@tormath1 I think i found the right way to do this. It also works as intended.

**Review by tormath1 — APPROVED** [review]
LGTM, thanks !

**Pull request merged**
